---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: secureplague

description: Secureblue with PlagueOS kernel.

base-image: ghcr.io/secureblue/silverblue-main-hardened
image-version: latest
...
